### PR TITLE
Support for Static export feature of Next.js

### PR DESCRIPTION
**Pull request by Sly777**

### CODE REVIEW

**Comment by Sly777** [comment]
hey @matthewmueller, do you plan to approve or reject this? I'm waiting for my boilerplate if you like it :)

**Comment by matthewmueller** [comment]
hey there, sorry for the delay on this. I think there's a more direct flag, like `ctx.export == true` that we should probably use instead.

**Comment by nfriedly** [comment]
Hey, this bit me too, and I created a new PR and then realized this one was here already. 

After reading your comments @matthewmueller, I went digging through the next.js docs and examples, but I don't see anything about a ctx.export flag. Perhaps it was there in a previous release?

Regardless, I think a pragmatic approach like this is the best option for right now, and I would appreciated this or #5 being merged in.

**Comment by matthewmueller** [comment]
Hey folks, do you have any interest in maintaining this? 

Please see #6

**Comment by nfriedly** [comment]
This is now released in next-cookies@1.0.3

**Pull request merged**
